// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CSAlert: typeof import('./src/components/common/CSAlert.vue')['default']
    CSButton: typeof import('./src/components/common/CSButton.vue')['default']
    CSModal: typeof import('./src/components/common/CSModal.vue')['default']
    CSTextField: typeof import('./src/components/common/CSTextField.vue')['default']
    FormAddActivity: typeof import('./src/components/Form/AddActivity.vue')['default']
    FormLogin: typeof import('./src/components/Form/Login.vue')['default']
    FormRegister: typeof import('./src/components/Form/Register.vue')['default']
    IconCircleInfo: typeof import('./src/assets/icons/IconCircleInfo.svg')['default']
    IconCircleNotch: typeof import('./src/assets/icons/IconCircleNotch.svg')['default']
    IconEllipsisVertical: typeof import('./src/assets/icons/IconEllipsisVertical.svg')['default']
    IconTrash: typeof import('./src/assets/icons/IconTrash.svg')['default']
    ListActivities: typeof import('./src/components/List/Activities.vue')['default']
    Navbar: typeof import('./src/components/Navbar/index.vue')['default']
  }
}

export { }
