// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CSAlert: typeof import('./src/components/common/CSAlert.vue')['default']
    CSButton: typeof import('./src/components/common/CSButton.vue')['default']
    CSTextField: typeof import('./src/components/common/CSTextField.vue')['default']
    FormLogin: typeof import('./src/components/Form/Login.vue')['default']
    'FormLogin copy': typeof import('./src/components/Form/Login copy.vue')['default']
    FormRegister: typeof import('./src/components/Form/Register.vue')['default']
    IconAdnBrands: typeof import('./src/assets/icons/IconAdnBrands.svg')['default']
    IconCircleInfo: typeof import('./src/assets/icons/IconCircleInfo.svg')['default']
    IconCircleNotch: typeof import('./src/assets/icons/IconCircleNotch.svg')['default']
    IconEllipsisVertical: typeof import('./src/assets/icons/IconEllipsisVertical.svg')['default']
    IconRefresh: typeof import('./src/assets/icons/IconRefresh.svg')['default']
    IconZ: typeof import('./src/assets/icons/IconZ.svg')['default']
    Navbar: typeof import('./src/components/Navbar/index.vue')['default']
  }
}

export { }
